"""
Demo data generator for the Sri Triveni High School management system.

Creates a realistic, completely fictional school for academic year 2026-27,
as of 23 September 2026 (Term 1 is over, Term 2 is due in October).

All names and phone numbers are made up. No real student data is used.

Usage:
    python generate_demo_data.py > seed_demo.sql
    psql -d school -f schema.sql
    psql -d school -f seed_demo.sql

The output is deterministic (fixed random seed), so everyone gets the same data.
"""

import random
from datetime import date, timedelta

random.seed(2026)

TODAY = date(2026, 9, 23)
YEAR_START = date(2026, 6, 1)
YEAR_END = date(2027, 4, 30)
SCHOOL_REOPENS = date(2026, 6, 12)
HOLIDAYS = {date(2026, 8, 15)}                 # Independence Day

# ---------------------------------------------------------------------------
# Name lists (common Telugu names, used only as fiction)
# ---------------------------------------------------------------------------
BOY_NAMES = ["Arjun", "Sai Kiran", "Rahul", "Karthik", "Vamsi", "Nikhil", "Charan",
             "Harsha", "Praneeth", "Rohith", "Srinivas", "Teja", "Varun", "Abhiram",
             "Manoj", "Sai Charan", "Venkat", "Yashwanth", "Akhil", "Bharath",
             "Chaitanya", "Dinesh", "Ganesh", "Hemanth", "Jaswanth", "Lokesh",
             "Mahesh", "Naveen", "Pavan", "Ravi Teja", "Sandeep", "Tarun", "Uday"]
GIRL_NAMES = ["Sneha", "Lakshmi", "Priya", "Divya", "Keerthi", "Harika", "Sravya",
              "Anusha", "Bhavana", "Deepika", "Gayathri", "Hasini", "Jahnavi",
              "Kavya", "Lasya", "Meghana", "Navya", "Pooja", "Ramya", "Sahithi",
              "Swathi", "Tejaswini", "Varshini", "Akshaya", "Charitha", "Geethika",
              "Mounika", "Nandini", "Pranathi", "Sindhu", "Vaishnavi", "Yamini"]
SURNAMES = ["Reddy", "Rao", "Naidu", "Varma", "Chowdary", "Goud", "Yadav", "Sharma",
            "Kumar", "Raju", "Babu", "Prasad", "Murthy", "Sastry", "Nayak", "Chary",
            "Patel", "Setty", "Mudiraj", "Kondapalli", "Gollapudi", "Bandi"]
FATHER_NAMES = ["Srinivas", "Ramesh", "Suresh", "Venkatesh", "Ravi", "Krishna",
                "Nagaraju", "Satyanarayana", "Prasad", "Rajesh", "Mohan", "Anil",
                "Madhu", "Srikanth", "Kiran", "Raghu", "Shankar", "Narasimha"]
MOTHER_NAMES = ["Lakshmi", "Padma", "Sujatha", "Radha", "Anitha", "Swapna",
                "Rani", "Jyothi", "Kalyani", "Sunitha", "Vani", "Madhavi"]

# Class ids 1..13 match the default data in schema.sql (Nursery=1 ... Class 10=13)
CLASS_NAMES = ["Nursery", "LKG", "UKG"] + [f"Class {i}" for i in range(1, 11)]
FEE = {"Tuition": 1, "Admission": 2, "Books": 3, "Uniform": 4, "Exam": 5, "Transport": 6}
SUBJ = {"Telugu": 1, "Hindi": 2, "English": 3, "Mathematics": 4,
        "Science": 5, "Social Studies": 6}
EXP_CAT = {"Salaries": 1, "Electricity": 2, "Water": 3, "Rent": 4, "Maintenance": 5,
           "Stationery": 6, "Transport fuel": 7, "Events": 8, "Miscellaneous": 9}

out = []


def emit(line=""):
    out.append(line)


def q(v):
    """Format a Python value as a SQL literal."""
    if v is None:
        return "NULL"
    if isinstance(v, bool):
        return "TRUE" if v else "FALSE"
    if isinstance(v, (int, float)):
        return str(v)
    if isinstance(v, date):
        return f"'{v.isoformat()}'"
    return "'" + str(v).replace("'", "''") + "'"


def insert(table, cols, rows, batch=500):
    for i in range(0, len(rows), batch):
        chunk = rows[i:i + batch]
        emit(f"INSERT INTO {table} ({', '.join(cols)}) VALUES")
        emit(",\n".join("  (" + ", ".join(q(v) for v in r) + ")" for r in chunk) + ";")


def rand_day(start, end):
    return start + timedelta(days=random.randint(0, (end - start).days))


def school_days(start, end):
    d = start
    while d <= end:
        if d.weekday() != 6 and d not in HOLIDAYS:   # skip Sundays and holidays
            yield d
        d += timedelta(days=1)


def band(class_id):
    if class_id <= 3:
        return "pre"      # Nursery, LKG, UKG
    if class_id <= 8:
        return "primary"  # Class 1-5
    if class_id <= 11:
        return "middle"   # Class 6-8
    return "high"         # Class 9-10


emit("-- Demo data for Sri Triveni High School (fictional). Generated by generate_demo_data.py")
emit("BEGIN;")

# ---------------------------------------------------------------------------
# Users (logins). Password hashes are placeholders, replaced by the real app.
# ---------------------------------------------------------------------------
users = [
    (1, "Demo Owner", "+919999900001", "owner@demo.school", "demo-not-a-real-hash", "owner", True),
    (2, "Demo Accountant", "+919999900002", "accounts@demo.school", "demo-not-a-real-hash", "accountant", True),
]

# ---------------------------------------------------------------------------
# Staff: 16 teachers (one class teacher per class + subject teachers), office, support
# ---------------------------------------------------------------------------
staff_rows, staff_users = [], []
staff_specs = ([("Teacher", 14000, 22000)] * 16 + [("Office Assistant", 11000, 13000)] +
               [("Driver", 12000, 14000)] * 2 + [("Ayah", 8000, 9000)] * 3 +
               [("Watchman", 9000, 10000)])
used_staff_names = set()
for sid, (designation, lo, hi) in enumerate(staff_specs, start=1):
    while True:
        if designation == "Teacher":
            female = random.random() < 0.65
        else:
            female = designation == "Ayah"
        first = random.choice(GIRL_NAMES if female else BOY_NAMES + FATHER_NAMES)
        name = f"{first} {random.choice(SURNAMES)}"
        if name not in used_staff_names:
            used_staff_names.add(name)
            break
    salary = round(random.randint(lo, hi) / 500) * 500
    joining = rand_day(date(2015, 6, 1), date(2026, 6, 1))
    user_id = None
    if designation == "Teacher":
        user_id = len(users) + 1
        users.append((user_id, name, f"+91999991{sid:04d}", None, "demo-not-a-real-hash", "teacher", True))
    staff_rows.append((sid, user_id, name, designation, f"+91999992{sid:04d}", joining, salary, True))

teacher_user_ids = [u[0] for u in users if u[5] == "teacher"]
insert("users", ["id", "full_name", "phone", "email", "password_hash", "role", "is_active"], users)
insert("staff", ["id", "user_id", "full_name", "designation", "phone", "joining_date",
                 "monthly_salary", "is_active"], staff_rows)
# class teacher for class c = teacher_user_ids[c-1]

# ---------------------------------------------------------------------------
# Academic year and terms
# ---------------------------------------------------------------------------
insert("academic_years", ["id", "name", "start_date", "end_date", "is_current"],
       [(1, "2026-27", YEAR_START, YEAR_END, True)])
term_due = {1: date(2026, 6, 15), 2: date(2026, 10, 15), 3: date(2027, 1, 15)}
insert("terms", ["id", "academic_year_id", "term_no", "name", "due_date"],
       [(t, 1, t, f"Term {t}", d) for t, d in term_due.items()])

# ---------------------------------------------------------------------------
# Fee structure (per class, per term, per fee type)
# ---------------------------------------------------------------------------
TUITION = {"pre": 3000, "primary": 4000, "middle": 5000, "high": 6000}
BOOKS = {"pre": 1200, "primary": 1800, "middle": 2400, "high": 3000}
EXAM = {"pre": 200, "primary": 300, "middle": 400, "high": 500}
fee_rows, fs_id = [], 0
structure = {}  # (class_id, term, head) -> amount
for c in range(1, 14):
    b = band(c)
    for t in (1, 2, 3):
        items = {"Tuition": TUITION[b], "Transport": 2500}
        if t == 1:
            items.update({"Admission": 5000, "Books": BOOKS[b], "Uniform": 1200})
        else:
            items["Exam"] = EXAM[b]
        for head, amt in items.items():
            fs_id += 1
            fee_rows.append((fs_id, c, t, FEE[head], amt))
            structure[(c, t, head)] = amt
insert("fee_structures", ["id", "class_id", "term_id", "fee_head_id", "amount"], fee_rows)

# ---------------------------------------------------------------------------
# Students, parents, enrollments
# ---------------------------------------------------------------------------
students, parents, links, enrollments = [], [], [], []
student_meta = {}   # enrollment_id -> dict
parent_id = 0
enr_id = 0
adm_counter = 1000
phone_counter = 10000
families = []       # reuse some parents for siblings

for c in range(1, 14):
    size = random.randint(22, 28)
    names_in_class = set()
    for roll in range(1, size + 1):
        enr_id += 1
        adm_counter += 1
        female = random.random() < 0.48
        surname = None
        sibling_family = None
        if families and random.random() < 0.12:          # sibling of an existing student
            sibling_family = random.choice(families)
            surname = sibling_family["surname"]
        surname = surname or random.choice(SURNAMES)
        while True:
            first = random.choice(GIRL_NAMES if female else BOY_NAMES)
            full = f"{first} {surname}"
            if full not in names_in_class:
                names_in_class.add(full)
                break
        age = c + 2                                       # Nursery ~3 years old
        dob = rand_day(date(2026 - age - 1, 6, 1), date(2026 - age, 5, 31))
        new_admission = random.random() < 0.10 or c == 1
        admitted = rand_day(date(2026, 4, 1), date(2026, 6, 10)) if new_admission \
            else date(2026 - random.randint(1, max(1, c - 1)), 6, 1)
        students.append((enr_id, f"STHS{adm_counter}", full,
                         "female" if female else "male", dob, admitted,
                         f"H.No. {random.randint(1, 40)}-{random.randint(1, 300)}, Demo Colony, Hyderabad",
                         "active"))
        if sibling_family:
            for pid, rel in sibling_family["parents"]:
                links.append((enr_id, pid, rel))
            sibling_family["children"].append(enr_id)
        else:
            fam = {"surname": surname, "parents": [], "children": [enr_id]}
            parent_id += 1
            phone_counter += 1
            lang = random.choices(["te", "en", "hi"], weights=[70, 22, 8])[0]
            parents.append((parent_id, f"{random.choice(FATHER_NAMES)} {surname}",
                            f"+9199999{phone_counter:05d}", None, lang,
                            f"{admitted.isoformat()} 10:00:00+05:30"))
            links.append((enr_id, parent_id, "father"))
            fam["parents"].append((parent_id, "father"))
            if random.random() < 0.45:                    # mother also registered
                parent_id += 1
                phone_counter += 1
                parents.append((parent_id, f"{random.choice(MOTHER_NAMES)} {surname}",
                                f"+9199999{phone_counter:05d}", None, lang,
                                f"{admitted.isoformat()} 10:00:00+05:30"))
                links.append((enr_id, parent_id, "mother"))
                fam["parents"].append((parent_id, "mother"))
            families.append(fam)
        enrollments.append((enr_id, enr_id, 1, c, roll))   # section id == class id (one section)
        student_meta[enr_id] = {
            "class": c, "new": new_admission,
            "transport": random.random() < 0.35,
            "concession": random.choice([0.25, 0.5]) if random.random() < 0.08 else 0,
            "payer": random.choices(["full", "partial", "none"], weights=[75, 15, 10])[0],
            "early_t2": random.random() < 0.18,
            "attendance": random.choices([0.95, 0.9, 0.72], weights=[70, 25, 5])[0],
            "ability": min(0.97, max(0.35, random.gauss(0.72, 0.13))),
        }

insert("students", ["id", "admission_no", "full_name", "gender", "date_of_birth",
                    "admission_date", "address", "status"], students)
insert("parents", ["id", "full_name", "whatsapp_number", "alternate_phone",
                   "preferred_language", "consent_given_at"], parents)
insert("student_parents", ["student_id", "parent_id", "relation"], links)
insert("enrollments", ["id", "student_id", "academic_year_id", "section_id", "roll_no"], enrollments)

# ---------------------------------------------------------------------------
# Dues generated from the fee structure
# ---------------------------------------------------------------------------
dues, due_id = [], 0
dues_by = {}   # (enr, term) -> list of (due_id, payable)
for e, m in student_meta.items():
    for t in (1, 2, 3):
        for head in ("Tuition", "Admission", "Books", "Uniform", "Exam", "Transport"):
            amt = structure.get((m["class"], t, head))
            if amt is None:
                continue
            if head == "Admission" and not m["new"]:
                continue
            if head == "Transport" and not m["transport"]:
                continue
            conc = round(amt * m["concession"]) if head == "Tuition" and m["concession"] else 0
            note = "Sibling concession" if conc else None
            due_id += 1
            dues.append((due_id, e, t, FEE[head], amt, conc, note))
            dues_by.setdefault((e, t), []).append((due_id, amt - conc))
insert("student_dues", ["id", "enrollment_id", "term_id", "fee_head_id", "amount",
                        "concession", "concession_note"], dues)

# ---------------------------------------------------------------------------
# Payments (receipt numbers assigned in date order, gap-free)
# ---------------------------------------------------------------------------
pay_plans = []   # (date, enrollment, [(due_id, amount)], mode)


def plan(e, t, day, fraction=1.0):
    items, remaining = [], None
    total = sum(p for _, p in dues_by[(e, t)])
    target = round(total * fraction / 100) * 100 if fraction < 1 else total
    remaining = target
    for d_id, payable in dues_by[(e, t)]:
        if remaining <= 0:
            break
        amt = min(payable, remaining)
        if amt > 0:
            items.append((d_id, amt))
            remaining -= amt
    mode = random.choices(["cash", "upi", "cheque"], weights=[60, 35, 5])[0]
    pay_plans.append((day, e, items, mode))


for e, m in student_meta.items():
    if m["payer"] == "full":
        if random.random() < 0.3:     # pays Term 1 in two instalments
            plan(e, 1, rand_day(date(2026, 6, 1), date(2026, 6, 20)), 0.5)
            first = pay_plans[-1][2]
            paid = dict(first)
            rest = [(d, p - paid.get(d, 0)) for d, p in dues_by[(e, 1)] if p - paid.get(d, 0) > 0]
            mode = random.choices(["cash", "upi"], weights=[55, 45])[0]
            pay_plans.append((rand_day(date(2026, 7, 1), date(2026, 8, 10)), e, rest, mode))
        else:
            plan(e, 1, rand_day(date(2026, 6, 1), date(2026, 7, 15)))
    elif m["payer"] == "partial":
        plan(e, 1, rand_day(date(2026, 6, 5), date(2026, 8, 20)), random.choice([0.4, 0.5, 0.6]))
    if m["early_t2"] and m["payer"] == "full":
        plan(e, 2, rand_day(date(2026, 9, 1), date(2026, 9, 22)))

pay_plans.sort(key=lambda p: (p[0], p[1]))
payments, pay_items = [], []
item_id = 0
cancel_ids = set(random.sample(range(1, len(pay_plans) + 1), 3))
cancel_reasons = ["Entered against wrong student", "Duplicate entry",
                  "Cheque bounced"]
extra_plans = []
for pid, (day, e, items, mode) in enumerate(pay_plans, start=1):
    amount = sum(a for _, a in items)
    ref = f"UPI{random.randint(10**11, 10**12 - 1)}" if mode == "upi" else \
          (f"CHQ{random.randint(100000, 999999)}" if mode == "cheque" else None)
    if pid in cancel_ids:
        reason = cancel_reasons.pop()
        payments.append((pid, 1, pid, e, amount, mode, ref, day, 2, "cancelled", reason, 1,
                         f"{day.isoformat()} 16:30:00+05:30"))
        if reason != "Cheque bounced":           # the family pays again correctly later
            extra_plans.append((day + timedelta(days=random.randint(1, 5)), e, items, "cash"))
    else:
        payments.append((pid, 1, pid, e, amount, mode, ref, day, 2, "valid", None, None, None))
    for d_id, a in items:
        item_id += 1
        pay_items.append((item_id, pid, d_id, a))

next_receipt = len(payments)
for day, e, items, mode in sorted(extra_plans):
    next_receipt += 1
    payments.append((next_receipt, 1, next_receipt, e, sum(a for _, a in items), mode, None,
                     day, 2, "valid", None, None, None))
    for d_id, a in items:
        item_id += 1
        pay_items.append((item_id, next_receipt, d_id, a))

insert("payments", ["id", "academic_year_id", "receipt_no", "enrollment_id", "amount", "mode",
                    "reference_no", "paid_on", "collected_by", "status", "cancel_reason",
                    "cancelled_by", "cancelled_at"], payments)
insert("payment_items", ["id", "payment_id", "due_id", "amount"], pay_items)
insert("receipt_counters", ["academic_year_id", "last_receipt_no"], [(1, next_receipt)])

# ---------------------------------------------------------------------------
# Staff advances and salaries (June, July, August paid; September not yet)
# ---------------------------------------------------------------------------
advances, adv_by_staff = [], {}
for i, sid in enumerate(random.sample(range(1, len(staff_rows) + 1), 4), start=1):
    amt = random.choice([2000, 3000, 5000])
    advances.append((i, sid, amt, rand_day(date(2026, 7, 1), date(2026, 8, 20)), 1,
                     "Personal advance, recover from August salary"))
    adv_by_staff[sid] = amt
insert("staff_advances", ["id", "staff_id", "amount", "given_on", "given_by", "note"], advances)

salaries, sal_id = [], 0
for month in (date(2026, 6, 1), date(2026, 7, 1), date(2026, 8, 1)):
    paid_on = date(month.year, month.month + 1, random.randint(1, 5))
    for s in staff_rows:
        sal_id += 1
        adv = adv_by_staff.get(s[0], 0) if month.month == 8 else 0
        mode = "bank" if s[3] == "Teacher" else "cash"
        salaries.append((sal_id, s[0], month, s[6], adv, 0, paid_on, mode, 1))
insert("salary_payments", ["id", "staff_id", "salary_month", "gross", "advance_deduction",
                           "other_deduction", "paid_on", "mode", "paid_by"], salaries)

# ---------------------------------------------------------------------------
# Expenses (with two planted anomalies for the AI to detect later)
# ---------------------------------------------------------------------------
expenses, exp_id = [], 0


def expense(cat, amount, vendor, desc, day, mode="cash", approved=True):
    global exp_id
    exp_id += 1
    expenses.append((exp_id, EXP_CAT[cat], amount, vendor, desc, day, mode, None, 2,
                     1 if approved else None, "valid", None))


last_power_bill = None
for mth in (6, 7, 8, 9):
    if mth <= 8:                      # each month's bill is paid on the 8th of the next month
        last_power_bill = random.randint(8500, 11500)
        expense("Electricity", last_power_bill, "TGSPDCL", "Monthly electricity bill",
                date(2026, mth + 1, 8), "upi")
    expense("Water", random.choice([1500, 1800, 2000]), "Sri Sai Water Tankers",
            "Drinking water cans", date(2026, mth, 5))
    expense("Rent", 25000, "Building owner", "Monthly building rent", date(2026, mth, 3), "bank")
    for _ in range(4 if mth < 9 else 3):
        expense("Transport fuel", random.randint(3200, 4200), "HP Petrol Bunk", "Diesel for school van",
                rand_day(date(2026, mth, 1), date(2026, mth, 22 if mth == 9 else 28)))
    for _ in range(random.randint(2, 4)):
        expense("Stationery", random.randint(400, 2500), "Vijaya Book Stall",
                random.choice(["Chalk and dusters", "Register books", "Printer paper",
                               "Exam answer sheets", "Markers"]),
                rand_day(date(2026, mth, 1), date(2026, mth, 22 if mth == 9 else 28)))
    for _ in range(random.randint(1, 2)):
        expense("Maintenance", random.randint(800, 4500), "Local technician",
                random.choice(["Fan repair", "Plumbing", "Bench repair", "Painting touch-up",
                               "Electrical wiring fix"]),
                rand_day(date(2026, mth, 1), date(2026, mth, 22 if mth == 9 else 28)))
expense("Events", 14500, "Various", "Independence Day celebrations", date(2026, 8, 14))
expense("Miscellaneous", 3200, "Medical Store", "First-aid kit refill", date(2026, 7, 9))
# Planted anomaly 1: unusually large maintenance bill, not approved
expense("Maintenance", 48000, "Local technician", "Roof repair", date(2026, 9, 10),
        mode="cash", approved=False)
# Planted anomaly 2: the August electricity bill (paid 8 Sept) recorded a second time
expense("Electricity", last_power_bill, "TGSPDCL", "Electricity bill payment", date(2026, 9, 11), "cash")
insert("expenses", ["id", "category_id", "amount", "vendor", "description", "spent_on", "mode",
                    "bill_photo_path", "recorded_by", "approved_by", "status", "cancel_reason"],
       expenses)

# ---------------------------------------------------------------------------
# Attendance (students and staff) for every school day so far
# ---------------------------------------------------------------------------
days = list(school_days(SCHOOL_REOPENS, TODAY - timedelta(days=1)))
att = []
for e, m in student_meta.items():
    marker = teacher_user_ids[m["class"] - 1]
    rate = m["attendance"]
    for d in days:
        # chronic absentees get worse in September (a pattern to detect)
        r = rate - 0.12 if (rate < 0.8 and d.month == 9) else rate
        roll = random.random()
        status = "P" if roll < r else ("L" if roll < r + (1 - r) * 0.3 else "A")
        att.append((e, d, status, marker))
insert("student_attendance", ["enrollment_id", "date", "status", "marked_by"], att, batch=2000)

s_att = []
for s in staff_rows:
    for d in days:
        roll = random.random()
        s_att.append((s[0], d, "P" if roll < 0.96 else ("L" if roll < 0.99 else "A"), 1))
insert("staff_attendance", ["staff_id", "date", "status", "marked_by"], s_att, batch=2000)

# ---------------------------------------------------------------------------
# Exams, subjects per class, marks
# ---------------------------------------------------------------------------
insert("exams", ["id", "academic_year_id", "name", "start_date", "is_published"],
       [(1, 1, "Unit Test 1", date(2026, 7, 20), True),
        (2, 1, "Quarterly", date(2026, 9, 14), False)])


def subjects_for(c):
    if c <= 3:
        return ["Telugu", "English", "Mathematics"]
    if c <= 8:
        return ["Telugu", "English", "Mathematics", "Science", "Social Studies"]
    return ["Telugu", "Hindi", "English", "Mathematics", "Science", "Social Studies"]


exam_subjects, marks, es_id = [], [], 0
es_lookup = {}
for exam_id, max_big in ((1, 25), (2, 100)):
    for c in range(1, 14):
        max_m = 25 if exam_id == 1 else (50 if c <= 3 else 100)
        for sub in subjects_for(c):
            es_id += 1
            exam_subjects.append((es_id, exam_id, c, SUBJ[sub], max_m))
            es_lookup[(exam_id, c, sub)] = (es_id, max_m)
insert("exam_subjects", ["id", "exam_id", "class_id", "subject_id", "max_marks"], exam_subjects)

for e, m in student_meta.items():
    marker = teacher_user_ids[m["class"] - 1]
    for exam_id in (1, 2):
        for sub in subjects_for(m["class"]):
            es, max_m = es_lookup[(exam_id, m["class"], sub)]
            if random.random() < 0.02:
                marks.append((es, e, None, True, marker))
                continue
            score = min(1.0, max(0.1, random.gauss(m["ability"], 0.08)))
            marks.append((es, e, round(score * max_m * 2) / 2, False, marker))
insert("marks", ["exam_subject_id", "enrollment_id", "marks_obtained", "is_absent", "entered_by"],
       marks, batch=2000)

# ---------------------------------------------------------------------------
# Move id sequences past the inserted rows
# ---------------------------------------------------------------------------
for table in ["users", "staff", "academic_years", "terms", "fee_structures", "students",
              "parents", "enrollments", "student_dues", "payments", "payment_items",
              "staff_advances", "salary_payments", "expenses", "exams", "exam_subjects"]:
    emit(f"SELECT setval(pg_get_serial_sequence('{table}', 'id'), (SELECT MAX(id) FROM {table}));")

emit("COMMIT;")
print("\n".join(out))
